### ISSUE TITLE
Auto Installation Script failed

### ISSUE THREAD

**Issue by plochu** [ictinnovations/ictfax#47]
Hi,
I used Auto Installation Script from your website.
Installation on VPS with fresh Centos 7 - updated with `yum update` to latest versions of packages.

1. I logged to VPS using user account (with sudo privileges)
2. I switched to root using `sudo su`
3. I downloaded installation script using generated link `curl -JO http://ictfax.org/__auto/download.php?id=****`
4. I started installation script `bash install.sh`

In the end console shows:
```
####################################################
#   ICTFAX INSTALLATION COMPLETED SUCCESSFULLY     #
####################################################
Please visit xxx.xxx.xxx.xxx
and using following information to access ICTFax web interface

email: xxx@xxx.xx
password: xxxxxx
```

When I try to open webpage in browser I just see "Testing 123...", Apache default test page.

I found in console that just before installation finish there were some errors:
```
ERROR 1046 (3D000) at line 1: No database selected
PHP Fatal error:  Uncaught exception 'ICT\Core\CoreException' with message 'Unable to connect database server error:' in /usr/ictcore/core/lib/DB.php:28
Stack trace:
#0 /usr/ictcore/core/lib/init.php(49): ICT\Core\DB::connect()
#1 /usr/ictcore/core/Core.php(16): require_once('/usr/ictcore/co...')
#2 /usr/ictcore/bin/sendmail/email_to_fax(18): include_once('/usr/ictcore/co...')
#3 {main}
  thrown in /usr/ictcore/core/lib/DB.php on line 28
install.sh: line 34: /bin/wget: No such file or directory

```

Any idea how to fix this?

**Comment by plochu** [comment]
I also found some more errors on console

```
kannel.service is not a native service, redirecting to /sbin/chkconfig.
Executing /sbin/chkconfig kannel on
Job for kannel.service failed because the control process exited with error code. See "systemctl status kannel.service" and "journalctl -xe" for details.
warning: %post(ictcore-kannel-1.0.3.17deead-main.el7.noarch) scriptlet failed, exit status 1
Non-fatal POSTIN scriptlet failure in rpm package ictcore-kannel-1.0.3.17deead-main.el7.noarch
```

**Comment by plochu** [comment]
found problem with ictcore.conf
installation script was not placing correct database credentials in it.
