### ISSUE TITLE
Issue with script

### ISSUE THREAD

**Issue by DCorwinTCS** [ictinnovations/ictfax#60]
I'm trying to run the script and I keep getting the following error:

`PHP Fatal error:  Uncaught exception 'ICT\Core\CoreException' with message 'Unable to connect database server error:' in /usr/ictcore/core/lib/DB.php:28

Stack trace:

#0 /usr/ictcore/core/lib/init.php(49): ICT\Core\DB::connect()

#1 /usr/ictcore/core/Core.php(16): require_once('/usr/ictcore/co...')

#2 /usr/ictcore/bin/sendmail/email_to_fax(18): include_once('/usr/ictcore/co...')

#3 {main}
  thrown in /usr/ictcore/core/lib/DB.php on line 28

`

I'm not sure if i can ignore this or if this is an issue. This is my first time trying out this software.

**Comment by fizaict** [comment]
Please follow the steps given on ICTCore website to install ICTCore. I think the issue is maybe because you didn't define the database configurations in `ictcore/etc/ictcore.conf`.

https://ictcore.org/guides/
